const express = require("express");
const cors = require("cors");
const role_table = require("./controller/RoleController.js");
// const userController = require("./controller/UserController.js");
// const roomController = require("./controller/RoomController.js");
// const reservationController = require("./controller/ReservationController.js");
// const flightReservationController = require("./controller/FlightReservationController.js");
// const accountStatusController = require("./controller/StatusController.js");
// const flightController = require("./controller/FlightController.js");
// const feedbackController = require("./controller/FeedbackController.js");
// const guideReservationController = require("./controller/GuideReservationController.js");
// const priceController = require("./controller/PriceController.js");
// const carController = require("./controller/CarController.js");
const app = express();
const router = require("./router.js");
app.use(cors());
app.use(express.json());
app.use("/Tourism", router);
app.listen(8008, () => {
  role_table.createAndPopulateRole();
  // userController.UserCheckTable();
  // roomController.RoomCheckTable();
  // reservationController.ReservationCheckTable();
  // flightReservationController.FlightReservationCheckTable();
  // accountStatusController.AccountStatusCheckTable();
  // flightController.FlightCheckTable();
  // feedbackController.FeedbackCheckTable();
  // guideReservationController.guideReservationCheckTable();
  // priceController.PriceCheckTable();
  // carController.CarCheckTable();
  console.log("Hello World!");
});
